[theme]
base = "dark"
primaryColor = "#ff3f6c"
backgroundColor = "#0e131f"
secondaryBackgroundColor = "#161d2f"
textColor = "#f1f5f9"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
